import { makeStyles } from "@material-ui/core";

const style = makeStyles((theme) => ({
  root: {
    position: "relative",
    height: "175px",
    width: "300px",
    minHeight: "175px",
    minWidth: "350px",
    borderRadius: "20px",
    backgroundColor: "white",
    margin: " 0 80px",
    display: "flex",
  },
  leftContainer: {
    width: "60%",
    position: "relative",
    "& img": {
      position: "absolute",
      width: "100%",
      bottom: "-5%",
      left: "-20%",
      userSelect: "none",
      draggable: "false",
      pointerEvents: "none",
    },
  },
  rightContainer: {
    width: "60%",
    height: "80%",
    margin: "auto",
    display: "flex",
    justifyContent: "space-evenly",
    alignItems: "flex-start",
    flexDirection: "column",
  },
  subtitle1: {
    color: "#04091e",
    letterSpacing: "1px",

    fontWeight: 500,
  },
  subtitle2: {
    color: "#6e7589",
    letterSpacing: "1px",
    fontSize: "1rem",
    fontWeight: 400,
  },
  button: {
    cursor: "pointer",
    position: "absolute",
    borderRadius: " 20px 0 20px 0",
    width: "80px",
    height: "50px",
    bottom: 0,
    right: 0,
    backgroundColor: theme.palette.blue,
    boxShadow: "5px 5px 6px #12264a",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  quantityTooltip: {
    display: "flex",
    justifyContent: "space-around",
    cursor: "default",
    alignItems: "center",
    position: "absolute",
    width: "0px",
    height: "60px",
    borderRadius: " 20px 0 20px 0",
    top: -10,
    right: 0,
    backgroundColor: theme.palette.blue,
    boxShadow: "5px 5px 6px #12264a",
    overflow: "hidden",
    "& svg": {
      cursor: "pointer",
    },
  },
  addToCart: {
    height: "40px",
    width: "40px",
    borderRadius: "50%",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
    display: "flex",
    backgroundColor: theme.palette.red,
    "&:before": {
      content: "''",
      width: "5px",
      height: "5px",
      border: "solid white",
      borderWidth: "2px 2px 0px 0px",
      transform: "rotate(45deg) translate(-1.5px,2px)",
    },
  },
}));
export default style;
